#• ▌ ▄ ·.       ▄▄▄▄· .▄▄ ·  ▄▄▄· ▄▄▄· ▄▄▌ ▐ ▄▌ ▐ ▄ ▄▄▄ .▄▄▄  ▄▄▌  ▪  • ▌ ▄ ·. ▪  ▄▄▄▄▄
#·██ ▐███▪▪     ▐█ ▀█▪▐█ ▀. ▐█ ▄█▐█ ▀█ ██· █▌▐█•█▌▐█▀▄.▀·▀▄ █·██•  ██ ·██ ▐███▪██ •██
#▐█ ▌▐▌▐█· ▄█▀▄ ▐█▀▀█▄▄▀▀▀█▄ ██▀·▄█▀▀█ ██▪▐█▐▐▌▐█▐▐▌▐▀▀▪▄▐▀▀▄ ██▪  ▐█·▐█ ▌▐▌▐█·▐█· ▐█.▪
#██ ██▌▐█▌▐█▌.▐▌██▄▪▐█▐█▄▪▐█▐█▪·•▐█ ▪▐▌▐█▌██▐█▌██▐█▌▐█▄▄▌▐█•█▌▐█▌▐▌▐█▌██ ██▌▐█▌▐█▌ ▐█▌·
#▀▀  █▪▀▀▀ ▀█▄▀▪·▀▀▀▀  ▀▀▀▀ .▀    ▀  ▀  ▀▀▀▀ ▀▪▀▀ █▪ ▀▀▀ .▀  ▀.▀▀▀ ▀▀▀▀▀  █▪▀▀▀▀▀▀ ▀▀▀
#Plugin made with love by TheViperShow <3.
chunk:
  enabled: true #this enabled/disables the plugin.
  limit: 2 #the maximum number of spawners inside a chunk allowed, NOTE: 0 ≤ limit ≤ 65536
  messages:
    - "%PREFIX% &cThis chunks has too many spawners &7(&cMAX: &f%MAX%&7)&r"
    #- "You can set as many messages as you want here."