#• ▌ ▄ ·.       ▄▄▄▄· .▄▄ ·  ▄▄▄· ▄▄▄· ▄▄▌ ▐ ▄▌ ▐ ▄ ▄▄▄ .▄▄▄  ▄▄▌  ▪  • ▌ ▄ ·. ▪  ▄▄▄▄▄
#·██ ▐███▪▪     ▐█ ▀█▪▐█ ▀. ▐█ ▄█▐█ ▀█ ██· █▌▐█•█▌▐█▀▄.▀·▀▄ █·██•  ██ ·██ ▐███▪██ •██
#▐█ ▌▐▌▐█· ▄█▀▄ ▐█▀▀█▄▄▀▀▀█▄ ██▀·▄█▀▀█ ██▪▐█▐▐▌▐█▐▐▌▐▀▀▪▄▐▀▀▄ ██▪  ▐█·▐█ ▌▐▌▐█·▐█· ▐█.▪
#██ ██▌▐█▌▐█▌.▐▌██▄▪▐█▐█▄▪▐█▐█▪·•▐█ ▪▐▌▐█▌██▐█▌██▐█▌▐█▄▄▌▐█•█▌▐█▌▐▌▐█▌██ ██▌▐█▌▐█▌ ▐█▌·
#▀▀  █▪▀▀▀ ▀█▄▀▪·▀▀▀▀  ▀▀▀▀ .▀    ▀  ▀  ▀▀▀▀ ▀▪▀▀ █▪ ▀▀▀ .▀  ▀.▀▀▀ ▀▀▀▀▀  █▪▀▀▀▀▀▀ ▀▀▀
#Plugin made by love by TheViperShow.
chunk:
  enabled: true #this enabled/disables the plugin.
  limit: 2 #the maximum number of spawners inside a chunk allowed, note: 0 ≤ limit ≤ 65536
  messages:
    - "&8[&aMobSpawnerLimit&8]&7: &6Chunk spawners limit reached!"
    #- "You can set as many messages as you want here."